# Change Projector Aspect Ratio
- alias: Change Projector Aspect Ratio
  trigger:
    platform: state
    entity_id: input_select.projector_aspect_ratio
  action:
    - service: mqtt.publish
      data_template:
        topic: home/serial/command
        payload: "{{ trigger.to_state.state }}"

# Change Projector Input (HDMI1, HDMI2, etc.)
- alias: Change Projector Input
  trigger:
    platform: state
    entity_id: input_select.projector_input
  action:
    - service: mqtt.publish
      data_template:
        topic: home/serial/command
        payload: "{{ trigger.to_state.state }}"

# Adjust Horizontal and Vertical Keystone
- alias: Adjust Keystone
  trigger:
    - platform: state
      entity_id: input_number.h_keystone
    - platform: state
      entity_id: input_number.v_keystone
  action:
    - service: mqtt.publish
      data_template:
        topic: home/serial/command
        payload: >
          {% if trigger.entity_id == 'input_number.h_keystone' %}
            Keystone-H {{ states('input_number.h_keystone') | int }}
          {% else %}
            Keystone-V {{ states('input_number.v_keystone') | int }}
          {% endif %}

# Adjust Image Shift (Horizontal and Vertical)
- alias: Adjust Image Shift
  trigger:
    - platform: state
      entity_id: input_number.image_shift_h
    - platform: state
      entity_id: input_number.image_shift_v
  action:
    - service: mqtt.publish
      data_template:
        topic: home/serial/command
        payload: >
          {% if trigger.entity_id == 'input_number.image_shift_h' %}
            Image-Shift-H {{ states('input_number.image_shift_h') | int }}
          {% else %}
            Image-Shift-V {{ states('input_number.image_shift_v') | int }}
          {% endif %}