input_select:
  projector_aspect_ratio:
    name: Projector Aspect Ratio
    options:
      - '4:3'
      - '16:9'
    initial: '16:9'

  projector_input:
    name: Projector Input
    options:
      - 'HDMI1'
      - 'HDMI2'
    initial: 'HDMI1'

input_number:
  h_keystone:
    name: Horizontal Keystone
    initial: 0
    min: -40
    max: 40
    step: 1

  v_keystone:
    name: Vertical Keystone
    initial: 0
    min: -40
    max: 40
    step: 1

  image_shift_h:
    name: Image Shift Horizontal
    initial: 0
    min: -250
    max: 250
    step: 1

  image_shift_v:
    name: Image Shift Vertical
    initial: 0
    min: -100
    max: 100
    step: 1